/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PALAVRAS_RESERVADAS = 1;
  /** RegularExpression Id. */
  int CONSTANTES_INTEIRAS = 2;
  /** RegularExpression Id. */
  int CONSTANTES_REAIS = 3;
  /** RegularExpression Id. */
  int CONSTANTES_LITERAIS = 4;
  /** RegularExpression Id. */
  int SIMBOLOS_ESPECIAIS = 5;
  /** RegularExpression Id. */
  int COMENTARIO = 10;
  /** RegularExpression Id. */
  int COMENTARIOS = 11;
  /** RegularExpression Id. */
  int COM = 12;
  /** RegularExpression Id. */
  int INVALID_CONST = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<PALAVRAS_RESERVADAS>",
    "<CONSTANTES_INTEIRAS>",
    "<CONSTANTES_REAIS>",
    "<CONSTANTES_LITERAIS>",
    "<SIMBOLOS_ESPECIAIS>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<COMENTARIO>",
    "<COMENTARIOS>",
    "<COM>",
    "<INVALID_CONST>",
  };

}
