/* Generated By:JavaCC: Do not edit this line. LexicoTokenManager.java */
import java.io.*;

/** Token Manager. */
public class LexicoTokenManager implements LexicoConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3f7ffa0L) != 0L)
            return 4;
         return -1;
      case 1:
         if ((active0 & 0x3f7ffa0L) != 0L)
            return 4;
         return -1;
      case 2:
         if ((active0 & 0x3f7f9a0L) != 0L)
            return 4;
         return -1;
      case 3:
         if ((active0 & 0x3f7b9a0L) != 0L)
            return 4;
         return -1;
      case 4:
         if ((active0 & 0x2d6a9a0L) != 0L)
            return 4;
         return -1;
      case 5:
         if ((active0 & 0x2d229a0L) != 0L)
            return 4;
         return -1;
      case 6:
         if ((active0 & 0x9021a0L) != 0L)
            return 4;
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 13:
         {
         jjmatchedKind = 43;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 33:
         {
         jjmatchedKind = 40;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 37:
         {
         jjmatchedKind = 28;
         jjmatchedPos = 0;
         }
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 38:
         return jjStopAtPos(0, 38);
      case 40:
         return jjStopAtPos(0, 1);
      case 41:
         return jjStopAtPos(0, 2);
      case 42:
         return jjStopAtPos(0, 31);
      case 43:
         return jjStopAtPos(0, 26);
      case 45:
         return jjStopAtPos(0, 30);
      case 47:
         return jjStopAtPos(0, 27);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x1400000000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x2800000000L);
      case 91:
         return jjStopAtPos(0, 3);
      case 93:
         return jjStopAtPos(0, 4);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2e00L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x48000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x80L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x100000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x4020L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x401000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x1010000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x2020000L);
      case 124:
         return jjStopAtPos(0, 39);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         break;
      case 37:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 29);
         break;
      case 60:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 61:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         break;
      case 62:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x200100L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x9000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2120000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x1010020L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0xe00L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x600L);
      case 61:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(2, 36);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(2, 37);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8080L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x801020L);
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x440000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x2124000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x1010000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8280L);
      case 101:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x110000L);
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x400800L);
      case 108:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 21, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x800100L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x2060000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0x11000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x500L);
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x100800L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x20L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x2020080L);
      case 121:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa6_0(active0, 0x48000L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x800020L);
      case 101:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x120000L);
      case 103:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 4);
         break;
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0xa00L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x12500L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x1080L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0x20800L);
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x12180L);
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x4400L);
      case 109:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 5, 4);
         break;
      case 110:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 23, 4);
         break;
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000L);
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 4);
         break;
      case 115:
         return jjMoveStringLiteralDfa7_0(active0, 0x200L);
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0x2180L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x400L);
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 115:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(7, 14);
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0xa00L);
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 98:
         return jjMoveStringLiteralDfa9_0(active0, 0x400L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 104:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(8, 12);
         break;
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x42180L);
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000L);
      case 104:
         return jjMoveStringLiteralDfa10_0(active0, 0x2180L);
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x10400L);
      case 110:
         return jjMoveStringLiteralDfa10_0(active0, 0x200L);
      case 115:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(9, 15);
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(10, 10);
         break;
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x2180L);
      case 115:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(10, 11);
         break;
      case 116:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(10, 9);
         else if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(10, 16);
         return jjMoveStringLiteralDfa11_0(active0, 0x40000L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 104:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000L);
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000L);
      case 115:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(11, 7);
         else if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(11, 8);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(11, 13);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000L);
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(12, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 115:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(13, 18);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 4;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  else if (curChar == 33)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 33)
                     kind = 6;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 4:
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 4 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\50", "\51", "\133", "\135", "\160\162\157\147\162\141\155", null, 
"\145\170\145\143\165\164\145\40\164\150\151\163", "\144\145\143\154\141\162\145\40\164\150\151\163", 
"\141\163\40\143\157\156\163\164\141\156\164", "\141\163\40\166\141\162\151\141\142\154\145", 
"\141\163\163\151\147\156\40\164\150\151\163", "\163\150\157\167\40\164\150\151\163", 
"\141\143\161\165\151\162\145\40\164\150\151\163", "\160\165\164\40\164\150\151\163", "\143\150\145\143\153\40\164\150\151\163", 
"\164\162\165\145\40\162\145\163\165\154\164", "\165\156\164\162\165\145\40\162\145\163\165\154\164", 
"\143\141\162\162\171\40\157\165\164\40\164\150\151\163", null, "\151\156\164\145\147\145\162", "\162\145\141\154", 
"\163\164\162\151\156\147", "\142\157\157\154\145\141\156", "\164\162\165\145", 
"\165\156\164\162\165\145", "\53", "\57", "\45", "\45\45", "\55", "\52", "\75\75", "\41\75", "\74\74", 
"\76\76", "\74\74\75", "\76\76\75", "\46", "\174", "\41", null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1ffffffffffL, 
};
static final long[] jjtoSkip = {
   0x3e0000000000L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[4];
static private final int[] jjstateSet = new int[8];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public LexicoTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public LexicoTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 4; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         curTokenImage = "";
      else
         curTokenImage = image.toString();
      beginLine = endLine = input_stream.getBeginLine();
      beginColumn = endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      curTokenImage = (im == null) ? input_stream.GetImage() : im;
      beginLine = input_stream.getBeginLine();
      beginColumn = input_stream.getBeginColumn();
      endLine = input_stream.getEndLine();
      endColumn = input_stream.getEndColumn();
   }
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 19;
   jjmatchedPos = -1;
   curPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static int[] jjemptyLineNo = new int[1];
static int[] jjemptyColNo = new int[1];
static boolean[] jjbeenHere = new boolean[1];
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 0 :
         break;
      case 1 :
        image.append(jjstrLiteralImages[1]);
        lengthOfMatch = jjstrLiteralImages[1].length();
                      System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 2 :
        image.append(jjstrLiteralImages[2]);
        lengthOfMatch = jjstrLiteralImages[2].length();
                          System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 3 :
        image.append(jjstrLiteralImages[3]);
        lengthOfMatch = jjstrLiteralImages[3].length();
                            System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 4 :
        image.append(jjstrLiteralImages[4]);
        lengthOfMatch = jjstrLiteralImages[4].length();
                            System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 5 :
        image.append(jjstrLiteralImages[5]);
        lengthOfMatch = jjstrLiteralImages[5].length();
                               System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 6 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                             System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 7 :
        image.append(jjstrLiteralImages[7]);
        lengthOfMatch = jjstrLiteralImages[7].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 8 :
        image.append(jjstrLiteralImages[8]);
        lengthOfMatch = jjstrLiteralImages[8].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 9 :
        image.append(jjstrLiteralImages[9]);
        lengthOfMatch = jjstrLiteralImages[9].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 10 :
        image.append(jjstrLiteralImages[10]);
        lengthOfMatch = jjstrLiteralImages[10].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 11 :
        image.append(jjstrLiteralImages[11]);
        lengthOfMatch = jjstrLiteralImages[11].length();
                                  System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 12 :
        image.append(jjstrLiteralImages[12]);
        lengthOfMatch = jjstrLiteralImages[12].length();
                              System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 13 :
        image.append(jjstrLiteralImages[13]);
        lengthOfMatch = jjstrLiteralImages[13].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 14 :
        image.append(jjstrLiteralImages[14]);
        lengthOfMatch = jjstrLiteralImages[14].length();
                            System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 15 :
        image.append(jjstrLiteralImages[15]);
        lengthOfMatch = jjstrLiteralImages[15].length();
                                System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 16 :
        image.append(jjstrLiteralImages[16]);
        lengthOfMatch = jjstrLiteralImages[16].length();
                                   System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 17 :
        image.append(jjstrLiteralImages[17]);
        lengthOfMatch = jjstrLiteralImages[17].length();
                                     System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 18 :
        image.append(jjstrLiteralImages[18]);
        lengthOfMatch = jjstrLiteralImages[18].length();
                                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 19 :
         if (jjmatchedPos == -1)
         {
            if (jjbeenHere[0] &&
                jjemptyLineNo[0] == input_stream.getBeginLine() &&
                jjemptyColNo[0] == input_stream.getBeginColumn())
               throw new TokenMgrError(("Error: Bailing out of infinite loop caused by repeated empty string matches at line " + input_stream.getBeginLine() + ", column " + input_stream.getBeginColumn() + "."), TokenMgrError.LOOP_DETECTED);
            jjemptyLineNo[0] = input_stream.getBeginLine();
            jjemptyColNo[0] = input_stream.getBeginColumn();
            jjbeenHere[0] = true;
         }
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                 System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 20 :
        image.append(jjstrLiteralImages[20]);
        lengthOfMatch = jjstrLiteralImages[20].length();
                               System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 21 :
        image.append(jjstrLiteralImages[21]);
        lengthOfMatch = jjstrLiteralImages[21].length();
                         System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 22 :
        image.append(jjstrLiteralImages[22]);
        lengthOfMatch = jjstrLiteralImages[22].length();
                             System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 23 :
        image.append(jjstrLiteralImages[23]);
        lengthOfMatch = jjstrLiteralImages[23].length();
                               System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 24 :
        image.append(jjstrLiteralImages[24]);
        lengthOfMatch = jjstrLiteralImages[24].length();
                         System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 25 :
        image.append(jjstrLiteralImages[25]);
        lengthOfMatch = jjstrLiteralImages[25].length();
                             System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 26 :
        image.append(jjstrLiteralImages[26]);
        lengthOfMatch = jjstrLiteralImages[26].length();
                     System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 27 :
        image.append(jjstrLiteralImages[27]);
        lengthOfMatch = jjstrLiteralImages[27].length();
                     System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 28 :
        image.append(jjstrLiteralImages[28]);
        lengthOfMatch = jjstrLiteralImages[28].length();
                      System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 29 :
        image.append(jjstrLiteralImages[29]);
        lengthOfMatch = jjstrLiteralImages[29].length();
                       System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 30 :
        image.append(jjstrLiteralImages[30]);
        lengthOfMatch = jjstrLiteralImages[30].length();
                       System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 31 :
        image.append(jjstrLiteralImages[31]);
        lengthOfMatch = jjstrLiteralImages[31].length();
                      System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 32 :
        image.append(jjstrLiteralImages[32]);
        lengthOfMatch = jjstrLiteralImages[32].length();
                        System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 33 :
        image.append(jjstrLiteralImages[33]);
        lengthOfMatch = jjstrLiteralImages[33].length();
                       System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 34 :
        image.append(jjstrLiteralImages[34]);
        lengthOfMatch = jjstrLiteralImages[34].length();
                           System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 35 :
        image.append(jjstrLiteralImages[35]);
        lengthOfMatch = jjstrLiteralImages[35].length();
                              System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 36 :
        image.append(jjstrLiteralImages[36]);
        lengthOfMatch = jjstrLiteralImages[36].length();
                             System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 37 :
        image.append(jjstrLiteralImages[37]);
        lengthOfMatch = jjstrLiteralImages[37].length();
                                System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 38 :
        image.append(jjstrLiteralImages[38]);
        lengthOfMatch = jjstrLiteralImages[38].length();
                     System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 39 :
        image.append(jjstrLiteralImages[39]);
        lengthOfMatch = jjstrLiteralImages[39].length();
                    System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      case 40 :
        image.append(jjstrLiteralImages[40]);
        lengthOfMatch = jjstrLiteralImages[40].length();
                     System.out.println(image + "\u005ct" + matchedToken.beginLine + "\u005ct" + matchedToken.beginColumn + "\u005ct" + matchedToken.kind);
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
