/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int PROGRAM = 8;
  /** RegularExpression Id. */
  int EXECUTE = 9;
  /** RegularExpression Id. */
  int DECLARE = 10;
  /** RegularExpression Id. */
  int CONSTANT = 11;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int ASSING = 13;
  /** RegularExpression Id. */
  int SHOW = 14;
  /** RegularExpression Id. */
  int ACQUIRE = 15;
  /** RegularExpression Id. */
  int PUT = 16;
  /** RegularExpression Id. */
  int CHECK = 17;
  /** RegularExpression Id. */
  int TRESULT = 18;
  /** RegularExpression Id. */
  int URESULT = 19;
  /** RegularExpression Id. */
  int CARRY = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int REAL = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int BOOLEAN = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int UNTRUE = 26;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 27;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 28;
  /** RegularExpression Id. */
  int HEX_LITERAL = 29;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 30;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 31;
  /** RegularExpression Id. */
  int EXPONENT = 32;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 33;
  /** RegularExpression Id. */
  int STRING_LITERAL = 34;
  /** RegularExpression Id. */
  int IDENTIFIER = 35;
  /** RegularExpression Id. */
  int UNDERSCORE = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int LPAREN = 39;
  /** RegularExpression Id. */
  int RPAREN = 40;
  /** RegularExpression Id. */
  int LBRACE = 41;
  /** RegularExpression Id. */
  int RBRACE = 42;
  /** RegularExpression Id. */
  int LBRACKET = 43;
  /** RegularExpression Id. */
  int RBRACKET = 44;
  /** RegularExpression Id. */
  int SEMICOLON = 45;
  /** RegularExpression Id. */
  int COMMA = 46;
  /** RegularExpression Id. */
  int DOT = 47;
  /** RegularExpression Id. */
  int SUM = 48;
  /** RegularExpression Id. */
  int DIV = 49;
  /** RegularExpression Id. */
  int DIVI = 50;
  /** RegularExpression Id. */
  int REST = 51;
  /** RegularExpression Id. */
  int MINUS = 52;
  /** RegularExpression Id. */
  int MULT = 53;
  /** RegularExpression Id. */
  int EQUAL = 54;
  /** RegularExpression Id. */
  int DIFF = 55;
  /** RegularExpression Id. */
  int LESSTHAN = 56;
  /** RegularExpression Id. */
  int GREATERTHAN = 57;
  /** RegularExpression Id. */
  int LESSEQUAL = 58;
  /** RegularExpression Id. */
  int GREATEREQUAL = 59;
  /** RegularExpression Id. */
  int AND = 60;
  /** RegularExpression Id. */
  int OR = 61;
  /** RegularExpression Id. */
  int NOT = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"program\"",
    "\"execute this\"",
    "\"declare this\"",
    "\"as constant\"",
    "\"as variable\"",
    "\"assign this\"",
    "\"show this\"",
    "\"acquire this\"",
    "\"put this\"",
    "\"check this\"",
    "\"true result\"",
    "\"untrue result\"",
    "\"carry out this\"",
    "\"integer\"",
    "\"real\"",
    "\"string\"",
    "\"boolean\"",
    "\"true\"",
    "\"untrue\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<UNDERSCORE>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"+\"",
    "\"/\"",
    "\"%\"",
    "\"%%\"",
    "\"-\"",
    "\"*\"",
    "\"==\"",
    "\"!=\"",
    "\"<<\"",
    "\">>\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
  };

}
